//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student_Subject_Grade
    {
        public long ID { get; set; }
        public Nullable<long> StudentID { get; set; }
        public Nullable<long> SubjectID { get; set; }
        public Nullable<int> GradeID { get; set; }
    
        public virtual tbl_Student tbl_Student { get; set; }
        public virtual tblGrade tblGrade { get; set; }
        public virtual tblSubject tblSubject { get; set; }
    }
}
