//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAcctGeneralSI_DT
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public decimal QTY { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal GrossTotal { get; set; }
        public string Currency { get; set; }
        public decimal CurrencyRate { get; set; }
        public Nullable<int> Discount { get; set; }
        public decimal DiscountAmount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryUser { get; set; }
        public bool isDeleted { get; set; }
        public bool isVoided { get; set; }
        public string VoidBy { get; set; }
        public Nullable<System.DateTime> VoidDate { get; set; }
        public Nullable<double> taxper { get; set; }
        public Nullable<decimal> taxamt { get; set; }
        public string PCTCODE { get; set; }
        public string RefUSIN { get; set; }
        public string Department { get; set; }
    }
}
