//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vListStudent
    {
        public long CID { get; set; }
        public long Userid { get; set; }
        public string Username { get; set; }
        public long S_ID { get; set; }
        public string CourseName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string RegistrationNumber { get; set; }
        public string Name { get; set; }
        public string subjectname { get; set; }
    }
}
