//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vListResult
    {
        public long ID { get; set; }
        public Nullable<long> StudentID { get; set; }
        public string StudentName { get; set; }
        public Nullable<long> SubjectID { get; set; }
        public string SNAME { get; set; }
        public Nullable<int> GradeID { get; set; }
        public string GNAME { get; set; }
    }
}
