//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vListSubject
    {
        public long S_ID { get; set; }
        public string Name { get; set; }
        public long Userid { get; set; }
        public string teacherName { get; set; }
        public long CID { get; set; }
        public string CourseName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> StudentCount { get; set; }
        public Nullable<int> AverageCount { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
